name: CarND-Traffic-Sign-Classifier-Project
dependencies:
- pip >= 9
- jupyter
- matplotlib
- numpy
- scipy
- scikit-learn
- pandas
- menpo::opencv3
- conda-forge::tensorflow=0.11.0
#- pip:
#  - tensorflow
